apiVersion: v1
data:
  config.yaml: |-
    externalRules:
    - seriesQuery: 'nginx_ingress_nginx_http_requests_total{class!=""}'
      resources:
        namespaced: false
      name:
        matches: "^(.*)_total"
        as: "http_requests_per_second"
      metricsQuery: 'sum(rate(<<.Series>>{<<.LabelMatchers>>}[30s])) by (<<.GroupBy>>)'
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: metrics-adapter
    app.kubernetes.io/name: prometheus-adapter
    app.kubernetes.io/version: 0.12.0
  name: adapter-config
  namespace: default
