apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: rust-server
  name: rust-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rust-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rust-server
    spec:
      containers:
      - image: 10.164.178.1:5000/rust-server-final
        name: rust-server
        ports:
        - containerPort: 8080
