apiVersion: v1
kind: Service
metadata:
  name: rust-service
spec:
  selector:
    app.kubernetes.io/name: rust-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
  externalIPs: ["10.164.178.101"]
