apiVersion: core.spinkube.dev/v1alpha1
kind: SpinApp
metadata:
  name: spin-rust-server
spec:
  image: "10.164.178.1:5000/spin-rust-server:latest"
  # image: "192.168.68.54:5000/spin-rust-server:latest"
  enableAutoscaling: true
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: spin-rust-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spin-rust-server
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: External
    external:
      metric:
        name: http_requests_per_second
      target:
        type: Value
        averageValue: 10
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spin-rust-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: nuhakala.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: spin-rust-server
            port:
              number: 80
---
